name: Build and Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      matrix:
        # os: [linux, windows, darwin]
        os: [darwin]
        # arch: [amd64, arm64]
        arch: [arm64]

    runs-on: ubuntu-latest

    environment: production

    env:
      SELF_UPDATE_PRIVATE_KEY: ${{ secrets.SELF_UPDATE_PRIVATE_KEY }}
      SELF_UPDATE_GH_TOKEN: ${{ secrets.SELF_UPDATE_GH_TOKEN }}
      SELF_UPDATE_PUBLIC_KEY: ${{ secrets.SELF_UPDATE_PUBLIC_KEY }}

    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Setup Repo
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: go mod tidy

      # - name: Run Unit Tests
      #   run: go test -v ./...

      # - name: Build cli
      #   run: go build -o ./selfupdate ./cmd/selfupdate/main.go

      - name: test env
        run: |
          echo "SELF_UPDATE_PRIVATE_KEY: $SELF_UPDATE_PRIVATE_KEY"
          echo "SELF_ECHO: $SELF_ECHO"
          length=$(echo -n "$SELF_UPDATE_PRIVATE_KEY" | wc -c)
          echo "Length of SELF_UPDATE_PRIVATE_KEY: $length"

      # - name: Create a Release
      #   run: |
      #     ./selfupdate github release --owner blockthrough --repo selfupdate.go --version ${{ github.ref }} --title ${{ github.ref }}

      # - name: Build cli for all OS
      #   run: |
      #     GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./selfupdate-${{ matrix.os }}-${{ matrix.arch }} ./cmd/selfupdate/main.go

      # - name: Release
      #   run: |
      #     ./selfupdate github upload --owner blockthrough --repo selfupdate.go --filename selfupdate-${{ matrix.os }}-${{ matrix.arch }}.sign --version ${{ github.ref }} --sign < ./selfupdate-${{ matrix.os }}-${{ matrix.arch }}
