name: Selfupdate.go
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    env:
      SELF_UPDATE_PRIVATE_KEY: ${{ secrets.SELF_UPDATE_PRIVATE_KEY }}
      SELF_UPDATE_PUBLIC_KEY: ${{ secrets.SELF_UPDATE_PUBLIC_KEY }}
      SELF_UPDATE_GH_TOKEN: ${{ secrets.SELF_UPDATE_GH_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Checking out ...
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Unit Tests
        run: go test -v ./...

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./selfupdate-linux-amd64 ./cmd/selfupdate/main.go
          GOOS=linux GOARCH=arm64 go build -o ./selfupdate-linux-arm64 ./cmd/selfupdate/main.go
          GOOS=windows GOARCH=amd64 go build -o ./selfupdate-windows-amd64 ./cmd/selfupdate/main.go
          GOOS=windows GOARCH=arm64 go build -o ./selfupdate-windows-arm64 ./cmd/selfupdate/main.go
          GOOS=darwin GOARCH=amd64 go build -o ./selfupdate-darwin-amd64 ./cmd/selfupdate/main.go
          GOOS=darwin GOARCH=arm64 go build -o ./selfupdate-darwin-arm64 ./cmd/selfupdate/main.go

      - name: Upload-Release
        run: |
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}.sign --version ${{ github.ref }} --sign < ./selfupdate-linux-amd64
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}.sign --version ${{ github.ref }} --sign < ./selfupdate-linux-arm64
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}.sign --version ${{ github.ref }} --sign < ./selfupdate-windows-amd64
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}.sign --version ${{ github.ref }} --sign < ./selfupdate-windows-arm64
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}.sign --version ${{ github.ref }} --sign < ./selfupdate-darwin-amd64
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}.sign --version ${{ github.ref }} --sign < ./selfupdate-darwin-arm64
