name: Build and Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    env:
      SELF_UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SELF_UPDATE_PRIVATE_KEY: ${{ secrets.SELF_UPDATE_PRIVATE_KEY }}
      SELF_UPDATE_PUBLIC_KEY: ${{ secrets.SELF_UPDATE_PUBLIC_KEY }}
      SELF_UPDATE_VERSION: ${{ github.ref_name }}

    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Setup Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Build temporary cli
        run: go build -o ./selfupdate ./cmd/selfupdate/main.go

      - name: Create a Release
        run: |
          ./selfupdate github release \
          --owner blockthrough \
          --repo selfupdate.go \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --title ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }}

      - name: Build Darwin amd64
        run: |
          GOOS=darwin GOARCH=amd64 \
          go build \
          -ldflags "-X main.Version=${{ env.SELF_UPDATE_VERSION }} -X main.PublicKey=${{ env.SELF_UPDATE_PUBLIC_KEY }}" \
          -o ./selfupdate-darwin-amd64 \
          ./cmd/selfupdate/main.go

      - name: Build Darwin arm64
        run: |
          GOOS=darwin GOARCH=arm64 \
          go build \
          -ldflags "-X main.Version=${{ env.SELF_UPDATE_VERSION }} -X main.PublicKey=${{ env.SELF_UPDATE_PUBLIC_KEY }}" \
          -o ./selfupdate-darwin-arm64 \
          ./cmd/selfupdate/main.go

      - name: Build Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 \
          go build \
          -ldflags "-X main.Version=${{ env.SELF_UPDATE_VERSION }} -X main.PublicKey=${{ env.SELF_UPDATE_PUBLIC_KEY }}" \
          -o ./selfupdate-linux-amd64 \
          ./cmd/selfupdate/main.go

      - name: Build Linux arm64
        run: |
          GOOS=linux GOARCH=arm64 \
          go build \
          -ldflags "-X main.Version=${{ env.SELF_UPDATE_VERSION }} -X main.PublicKey=${{ env.SELF_UPDATE_PUBLIC_KEY }}" \
          -o ./selfupdate-linux-arm64 \
          ./cmd/selfupdate/main.go

      - name: Upload Darwin amd64
        run: |
          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-darwin-amd64.sign \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} \
          --key ${{ env.SELF_UPDATE_PRIVATE_KEY }} < ./selfupdate-darwin-amd64

          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-darwin-amd64 \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} < ./selfupdate-darwin-amd64

      - name: Upload Darwin arm64
        run: |
          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-darwin-arm64.sign \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} \
          --key ${{ env.SELF_UPDATE_PRIVATE_KEY }} < ./selfupdate-darwin-arm64

          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-darwin-arm64 \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} < ./selfupdate-darwin-arm64

      - name: Upload Linux amd64
        run: |
          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-linux-amd64.sign \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} \
          --key ${{ env.SELF_UPDATE_PRIVATE_KEY }} < ./selfupdate-linux-amd64

          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-linux-amd64 \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} < ./selfupdate-linux-amd64

      - name: Upload Linux arm64
        run: |
          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-linux-arm64.sign \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} \
          --key ${{ env.SELF_UPDATE_PRIVATE_KEY }} < ./selfupdate-linux-arm64

          ./selfupdate github upload \
          --owner blockthrough \
          --repo selfupdate.go \
          --filename selfupdate-linux-arm64 \
          --version ${{ env.SELF_UPDATE_VERSION }} \
          --token ${{ env.SELF_UPDATE_GH_TOKEN }} < ./selfupdate-linux-arm64
