name: Build and Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    env:
      SELF_UPDATE_PRIVATE_KEY: ${{ secrets.SELF_UPDATE_PRIVATE_KEY }}
      SELF_UPDATE_PUBLIC_KEY: ${{ secrets.SELF_UPDATE_PUBLIC_KEY }}
      SELF_UPDATE_GH_TOKEN: ${{ secrets.SELF_UPDATE_GH_TOKEN }}

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Setup Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./selfupdate-${{ matrix.os }}-${{ matrix.arch }} ./cmd/selfupdate/main.go

      - name: Release
        run: |
          ./selfupdate-linux-amd64 github release --owner blockthrough --repo selfupdate.go --name selfupdate-${{ matrix.os }}-${{ matrix.arch }}.sign --version ${{ github.ref }} --sign < ./selfupdate-${{ matrix.os }}-${{ matrix.arch }}
